spring:
  application:
    name: chawchaw
  profiles: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <>
    username: <>
    password: <>
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false
  redis:
    host: <>
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: <>
    password: <>
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  servlet:
    multipart:
      enabled: true
      location: <>
      max-request-size: 30MB
      max-file-size: 10MB
server:
  port: 8080

logging:
  slack:
    webhook-uri: <>
  config: classpath:logback-spring.xml

token:
  secret: <>
  expiration_time: 1800000
  prefix: "Bearer "
  header: "Authorization"

kakao:
  client-id: <>
  redirect-url: <>

user:
  profile:
    image:
      path: <>
      default: <>

front:
  domain: <>
  domain-local: <>