spring:
  application:
    name: chawchaw
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(Ecy8VmSmc9cY7jEq1ty/JGU7otnjmUTv2E+yEuYV29eBDqz2phtB5XghaU8xng32xr/ojm3x28Z2z1135AcWuj7Z7ufAoiOdVUOq+j3xwzznnQgw1Xv15ugXuUsQ/N9D)
    username: ENC(0PPMfXcDLXBPHB8gORuMOzxmHp0nkq/X)
    password: ENC(bT9KDS1iJ3bXh1SJWAB0WYIIF+V8pi7F)
    # initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    open-in-view: false
  redis:
    host: ENC(qA9TKyHjKryvhDcinHStA+KbvGsG4He6ReJ/xBVge1snn2TgV3ly6Ds4lon63R00yik9nHRFlnRitFoBc83etQ==)
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(3ABbRmcV8L8mvklBKleomk7xxBmWWrFvJ9DTaeU1+ws=)
    password: ENC(iAbW0/N7pxrKlv2jC2fLzjtAQpsnmmvhzANXWr8UKjA=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  servlet:
    multipart:
      enabled: true
      location: ENC(NtAteOeZgAHlGk88gVPsXjilcfhp3X6UgIpK8XzvbYc=)
      max-request-size: 30MB
      max-file-size: 10MB
server:
  port: 8080

logging:
  slack:
    webhook-uri: ENC(KdDchsPOKPC5qM06L8kp7oAwDzI0F/WWeA/AlMNlvP6as6XJQGb7Is/ERIV97yLP+Nr2jrhRDk5l13TDQV4yIXuqJXbe6HTu/ENAsgOnSU9y/H7IaowGo1Qvf/DV9eLH)
  config: classpath:logback-spring.xml

cloud:
  aws:
    credentials:
      accessKey: ENC(dHWd9ZNvYcPTg0kHeJx9zIL1DcoRH9Z6NBQbws79DGs=)
      secretKey: ENC(KL1ejN+Jmr7DvYKvvzxou1XbZJqixbWcbpbPLBbyIeLj9HkQBAi/VWJff/ohELo4d8wStFvXo/s=)
    s3:
      bucket: chawchaw-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false
  front:
    domain: ENC(C7j3EacHkyPZ3sahNKbxbLeRn5TbDfzqh5FqrIRNNrOPNepTanGFdlRewuEg44yz)

token:
  secret: ENC(QX+myqe9PjucIqYzu10EV6rcJGw6kLuTvJ+oNEyg5FBUQj+4fwr1Fg==)
  prefix: "Bearer "
  access:
    header: "Authorization"
    expiration_time: 1800000
  refresh:
    header: "RefreshToken"
    expiration_time: 604800000

social:
  secret: ENC(7GqitJ4IAqyZEfAX2vomaLIpuq+EAKR4)

kakao:
  client-id: ENC(wmC0qpzlyZWYjuSdwZ9cWQp+pZiqHWhaRwFOdyNROcEkTwQ2VSqkO5k/JVY7fUk1)
  redirect-url: ENC(8+JWpnGGYM2CtLgk6l1SCuNF064w46jY9TFtyXt4964WKojQWoLGKRNNrr3DZftwG7kcySC0tLQ=)

user:
  profile:
    image:
      path: ENC(Fke23brAMfUBV6vGZ+zWyDcn1vbw6QU7UaBEW1BirFkPECpbK55gZA==)
      default: ENC(Zk/rzdw9BVlrbVl7LydQ+eqsUuVVFYaR)


front:
  domain: ENC(a5iMuie2y023eDjz6/R21NkGZvyLf5flteF9vX7zopL8LGI53hyybQ==)
  domain-local: ENC(Ghnbc6J1hFhXckAGClRjiWEM2kvUe9Fs4/d5pRQd3Kg=)

redis:
  block:
    prefix: "block::"
  message:
    prefix: "message::"
    expiration-time: 1800
  like:
    prefix: "like::"
    expiration-time: 604800
  views:
    prefix: "views::"
    expiration-time: 86400
  viewDuplex:
    prefix: "viewDuplex::"
    expiration-time: 86400